url: http://aviflax.com
name: aviflax.com
title: aviflax.com
author: Avi Flax
email: avi@aviflax.com
twitter_username: flaximus_prime
github_username: aviflax
description: ""
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
paginate: 50
paginate_path: "/page/:num/"
feed:
  path: feed # This is the feed URL I was using with WordPress. I want it to keep working.
